#!/bin/bash
set -e

[ -z "$NEW_RELIC_APP_NAME"     ] && export NEW_RELIC_APP_NAME="KoBoForm Legacy"
[ -z "$NEW_RELIC_ENABLED"      ] && export NEW_RELIC_ENABLED=false
[ -z "$NEW_RELIC_LICENSE_KEY"  ] && export NEW_RELIC_LICENSE_KEY="LICENSE"

if [ "$NEW_RELIC_ENABLED" == "true" ]; then
    echo "new relic is enabled."
    exec newrelic-admin run-program /usr/local/bin/uwsgi --ini /srv/src/koboform.ini
else
    echo "new relic is disabled."
    exec /usr/local/bin/uwsgi --ini /srv/src/koboform.ini
fi
