#!/bin/bash
set -e

[ -z "$NEW_RELIC_APP_NAME"     ] && export NEW_RELIC_APP_NAME="KoboCat"
[ -z "$NEW_RELIC_ENABLED"      ] && export NEW_RELIC_ENABLED=false
[ -z "$NEW_RELIC_LICENSE_KEY"  ] && export NEW_RELIC_LICENSE_KEY="LICENSE"

if [ "$NEW_RELIC_ENABLED" == "true" ]; then
    echo "new relic is enabled."
    /sbin/setuser wsgi newrelic-admin run-program /usr/local/bin/uwsgi --ini /srv/src/kobocat.ini
else
    echo "new relic is disabled."
    /sbin/setuser wsgi /usr/local/bin/uwsgi --ini /srv/src/kobocat.ini
fi
